spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dy_api
    username: ${spring.datasource.password}
    password: ${spring.datasource.password}